USE master
GO

CREATE DATABASE dbTimeSheet
GO

CREATE TABLE tblPermission
(
	IDPermission INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Permission VARCHAR(50) NOT NULL
);
GO

CREATE TABLE tblUser
(
	IDUser INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	FKPermission INT FOREIGN KEY REFERENCES tblPermission NOT NULL,
	Firstname NVARCHAR(100) NOT NULL,
	Lastname NVARCHAR(100) NOT NULL,
	UserShortcut NVARCHAR(10),
	Street NVARCHAR(150) NOT NULL,
	Number VARCHAR(10) NOT NULL,
	Stage VARCHAR(10),
	Door VARCHAR(10),
	Place VARCHAR(100) NOT NULL,
	ZIPCode VARCHAR(10) NOT NULL,
	Department NVARCHAR(100) NOT NULL,
	Email NVARCHAR(MAX) 
);
GO

CREATE TABLE tblTime
(
	IDTime INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	FKUser INT FOREIGN KEY REFERENCES tblUser NOT NULL,
	StartTime DATETIME DEFAULT GETDATE() NOT NULL,
	EndTime DATETIME,
	[Description] NVARCHAR(255),
	State VARCHAR(30) NOT NULL,
	TotalTime DECIMAL
);
GO